
amazonProperties:
  endpointUrl: s3.ap-south-1.amazonaws.com/BUCKETNAME/
#  endpointUrl: https://855898191720.signin.aws.amazon.com/console
  accessKey: ********
  secretKey: ********
  bucketName: bucketName
